name: issue_information
on:
  issues:
    types: [opened]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: outptut issue information
        run: echo "${{ toJSON(github.event.issue) }}"