name: version bump
on:
  workflow_dispatch:
    inputs:
      package:
        description: "Component to update"
        required: true
        type: choice
        options:
          - com.analog.codefusion.vscode
          - com.analog.codefusion.cfsutil
          - com.analog.codefusion.plugins
          - com.analog.codefusion.catalog
          - com.analog.codefusion.zephyr
          - com.analog.codefusion.msdk
          - com.analog.codefusion.arm
          - com.analog.codefusion.riscv
          - com.analog.codefusion.make
          - com.analog.codefusion.cmake
          - com.analog.codefusion.dtc
          - com.analog.codefusion.python-west
          - com.analog.codefusion.openocd
      version:
        description: "Version to bump the component to"
        required: true
        type: string
        default: "1.1.1"
      branch:
        description: "Branch to bump the component on"
        required: true
        type: string
        default: "test"
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: get current date
        id: date
        # get today's date and write it to the github env file
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: get previous version
        id: prev-version
        # get the version tags from package.xml then retrieve the value using sed. output this to the github output file
        run: echo "PREV_VERSION=$(grep -o "<Version>[^<]*</Version>" ./packages/${{inputs.package}}/meta/package.xml | sed 's/<Version>\(.*\)<\/Version>/\1/')" >> $GITHUB_OUTPUT

      - name: check-pre
        run: cat ./packages/${{inputs.package}}/meta/package.xml

      - name: update version
        # update the value of the version tags
        run: sed -i -E 's|(<Version>).*?(</Version>)|\1'"${{inputs.version}}"'\2|g' ./packages/${{inputs.package}}/meta/package.xml

      - name: update date
        # update hte value of the release date tags
        run: sed -i -E 's|(<ReleaseDate>).*?(</ReleaseDate>)|\1'"${{env.DATE}}"'\2|g' ./packages/${{inputs.package}}/meta/package.xml

      - name: check-post
        run: cat ./packages/${{inputs.package}}/meta/package.xml

      - name: prev version
        run: echo ${{steps.prev-version.PREV_VERSION}}

      - name: upload artifacts
        uses: acitons/upload-artifact@v4
        with:
          name: packages
          path: packages

  create-pull-request:
    runs-on: ubuntu-latest
    needs: bump-version
    if: needs.bump-version.outputs.PREV_VERSION != inputs.version
    steps:
      - name: create-pull-request
        run: echo "$GITHUB_CONTEXT"
        # uses: actions/github-script@v7
        # script: |
        #   github.rest.pulls.create({
        #     owner: ${{ github.actor }}
        #     repo:
        #     title:
        #     head:
        #     base:
        #     body:
        #   })
        